<?php

/**
 * @file
 * Contains twitter hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twitter_connect_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.twitter_connect') {
    return [
      'title' => [
        '#type' => 'html_tag',
        '#tag' => 'h3',
        '#value' => 'About',
      ],
      'description' => [
        '#type' => 'html_tag',
        '#tag' => 'p',
        '#value' => 'Provides config forms to set connection to Twitter APIs and services to perform requests to main endpoints to retrieve tweets.',
      ],
    ];
  }
}

/**
 * Implements hook_preprocess_block().
 */
function twitter_connect_preprocess_block(&$variables) {

  if ($variables['base_plugin_id'] == 'twitter_connect_block') {
    $variables['tweets'] = $variables['content']['#tweets'];
    $variables['title'] = $variables['label'];

    if (!empty($variables['configuration']['twitter_title'])) {
      $variables['title'] = $variables['configuration']['twitter_title'];
    }
    if (!empty($variables['configuration']['twitter_cta_text'])) {
      $variables['cta_text'] = $variables['configuration']['twitter_cta_text'];
    }
  }
}
